[build-system]
requires = ["setuptools", "Cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "PyRAI2MD"
version = "2.1.0"
authors = [
    {name = "Jingbai Li"},
]
description="Python Rapid Artificial Intelligence Ab Initio Molecular Dynamics."
dependencies = ['numpy', "scikit-learn", "matplotlib"]
readme = "README.md"
requires-python = ">=3.8"

classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Information Analysis",
        "Topic :: Scientific/Engineering :: Physics",
        "Topic :: Scientific/Engineering :: Chemistry",
        "Topic :: Software Development :: Libraries :: Python Modules"
        ]

[project.optional-dependencies]
tf = ["tensorflow>=2.3.0"]
tf_gpu = ["tensorflow-gpu>=2.3.0"]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["TEST*"]
namespaces = false

[tool.setuptools]
include-package-data = false